results

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -79,6 +79,41 @@ jobs:
               --output-format=text \
               --log-level=debug \
               --return-error || true
+  sca_security_test:
+    name: SCA Security Test
+    runs-on: ubuntu-latest
+    needs: [pre_build]
+    env:
+      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Install dependencies
+        run: npm install
+
+      - name: Run Snyk SCA
+        run: |
+          docker run --rm \
+            --name sca \
+            -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
+            -v $(pwd):/app \
+            snyk/snyk:node test --all-projects || true
+
+      - name: Check Snyk Findings
+        run: |
+          docker logs sca > container-logs.txt
+
+          echo "🔍 Snyk Output:"
+          cat container-logs.txt
+
+          if grep -E 'found [1-9][0-9]* vulnerabilities' container-logs.txt; then
+            echo "❌ Vulnerabilities found. Failing the job."
+            exit 1
+          else
+            echo "✅ No vulnerabilities found."
+          fi
 
   sca:
     name: SCA Security Test
@@ -202,7 +237,7 @@ jobs:
           docker run --rm \
             --network devsecopsbootstrap_default \
             -v $(pwd):/zap/wrk/:rw \
-            ghcr.io/zaproxy/zap-full-scan \
+            ghcr.io/zaproxy/zaproxy:weekly \
             -t http://backend-api:5000 \
             -r zap-fullscan-report.html \
             -w zap-fullscan-report.md \
