Horsec

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -18,6 +18,15 @@ jobs:
     - name: Checkout Code
       uses: actions/checkout@v4
 
+    - name: Set up Docker
+      uses: docker/setup-buildx-action@v3
+
+    - name: Docker Login
+      uses: docker/login-action@v2
+      with:
+          username: 'olayiwola1'
+          password: 'dckr_pat_o1gQPIEJCWEtG-gFWeBjFsf_Kcg'
+
     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
@@ -94,4 +103,21 @@ jobs:
           -Dsonar.host.url=$SONAR_HOST_URL \
           -Dsonar.login=$SONAR_TOKEN \
          
-        
+  static_analysis:
+    name: SAST Analysis
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Run Horusec SAST
+        run: |
+            docker run --name horusec -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src horuszup/horusec-cli:v2.7 horusec start -p /src -P $(pwd) || true
+            docker logs horusec > container-logs
+            if [[ "$(grep 'Vulnerability MEDIUM is. [1-9]\d*' container-logs | wc -l)" -gt 0 ]]; then
+              echo 'Failing job due to identified failures'
+              exit 1
+            else
+              echo "no issues found"
+            fi
